"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--color-background)]">
      <header className="sticky top-0 z-40 flex h-14 items-center gap-3 border-b border-[var(--color-border)] bg-[var(--color-background)]/95 backdrop-blur-sm px-4 pt-[env(safe-area-inset-top)]">
        <Link
          href="/settings"
          className="p-2 -ml-2 rounded-lg hover:bg-[var(--color-muted)] transition-colors"
          aria-label="Back"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="m15 18-6-6 6-6" />
          </svg>
        </Link>
        <h1 className="text-lg font-semibold">Terms of Service</h1>
      </header>

      <main className="mx-auto max-w-2xl px-4 py-8 space-y-6 text-sm text-[var(--color-foreground)] leading-relaxed">
        <p className="text-[var(--color-muted-foreground)]">Effective date: March 4, 2026</p>

        <p>
          By using Selah (&ldquo;the app&rdquo;), you agree to these terms. If you do not agree,
          please do not use the app.
        </p>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">1. What Selah provides</h2>
          <p>
            Selah is a free Bible study tool that lets you read, compare translations, listen to
            chapters, take notes, and explore AI-generated scholarly perspectives. All features
            are provided at no cost.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">2. Accounts</h2>
          <p>
            Creating an account is optional. If you create one, you are responsible for keeping
            your credentials secure. We may suspend or delete accounts that are used to abuse
            the service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">3. Bible text</h2>
          <p>
            Bible translations are sourced from third-party providers (bible.helloao.org and
            others). Public-domain translations are freely available. Copyrighted translations
            are displayed under the terms of their respective publishers. We do not claim
            ownership of any Bible text.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">4. AI-generated content</h2>
          <p>
            Scholarly perspectives are generated by Google&rsquo;s Gemini AI and are provided for
            educational and devotional purposes only. AI responses may contain inaccuracies.
            They do not represent the views of any denomination, institution, or individual scholar.
            Always verify important claims with authoritative sources.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">5. Your content</h2>
          <p>
            Notes you create belong to you. We do not read, analyze, or share your notes.
            If you enable sync, your notes are stored in Firebase to provide cross-device access.
            You may delete your notes at any time.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">6. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Abuse the AI features by submitting excessive or automated requests</li>
            <li>Attempt to reverse-engineer, scrape, or overload the service</li>
            <li>Use the app for any unlawful purpose</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">7. Availability</h2>
          <p>
            We strive to keep Selah available but make no guarantees of uptime. The app may be
            temporarily unavailable for maintenance or due to circumstances beyond our control.
            We may modify or discontinue features at any time.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">8. Limitation of liability</h2>
          <p>
            Selah is provided &ldquo;as is&rdquo; without warranties of any kind. To the fullest
            extent permitted by law, we are not liable for any damages arising from your use of
            the app, including but not limited to reliance on AI-generated content.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">9. Changes</h2>
          <p>
            We may update these terms from time to time. Continued use of the app after changes
            constitutes acceptance of the revised terms.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold">10. Contact</h2>
          <p>
            Questions about these terms? Email us at{" "}
            <a href="mailto:twototangodev@gmail.com" className="text-[var(--color-accent)] hover:underline">
              twototangodev@gmail.com
            </a>.
          </p>
        </section>
      </main>
    </div>
  );
}
